"""Integration tests against REAL meeting data and known-good outputs.

Unit tests with fakes prove logic in isolation; these prove the actual
pipeline functions reproduce the actual outputs sitting in the user's
meetings repo. flatten() is deterministic, so for a meeting whose
transcript-readable.txt was generated by the current pipeline, re-running
flatten on a COPY of its transcript.json must reproduce the existing file
byte-for-byte.

Real data lives outside this (public) repo, so nothing is committed here:
tests discover the meetings root via the WS_MEETINGS_DIR env var, falling
back to the conventional sibling-repo location. Every test SKIPS cleanly
when the data, or numpy/scipy, is unavailable.

Run under the app venv:

    whisper-env/Scripts/python.exe -m unittest tests.test_real_meeting_data -v
"""

import json
import os
import shutil
import tempfile
import unittest
from pathlib import Path

try:
    import numpy  # noqa: F401
    import scipy.signal  # noqa: F401
    _HAS_DEPS = True
except ImportError:
    _HAS_DEPS = False


def _meetings_root() -> Path | None:
    env = os.environ.get("WS_MEETINGS_DIR")
    if env:
        p = Path(env)
        return p if p.exists() else None
    # Conventional layout: this repo at .../pendentive/whisper-sync,
    # meetings at .../icustomer/ic-product-mgmt/meetings/in-house
    candidate = (
        Path(__file__).resolve().parents[1].parent.parent
        / "icustomer" / "ic-product-mgmt" / "meetings" / "in-house"
    )
    return candidate if candidate.exists() else None


def _complete_meetings(root: Path, limit: int = 5) -> list[Path]:
    """Most recent meetings that have ALL pipeline outputs (known-good)."""
    found = []
    for week_dir in sorted(root.iterdir(), reverse=True):
        if not week_dir.is_dir() or week_dir.name.startswith("."):
            continue
        for mdir in sorted(week_dir.iterdir(), reverse=True):
            if not mdir.is_dir():
                continue
            if all(
                (mdir / f).exists()
                for f in ("transcript.json", "transcript-readable.txt", "minutes.md")
            ):
                found.append(mdir)
                if len(found) >= limit:
                    return found
    return found


_ROOT = _meetings_root()
_MEETINGS = _complete_meetings(_ROOT) if _ROOT else []


@unittest.skipUnless(_HAS_DEPS, "requires numpy/scipy (run under app venv)")
@unittest.skipUnless(_MEETINGS, "no real meeting data found (set WS_MEETINGS_DIR)")
class RealMeetingDataTests(unittest.TestCase):
    """Each test runs against up to 5 recent complete real meetings."""

    def _tmp_copy(self, meeting_dir: Path, tmp: str) -> Path:
        """Copy transcript.json into tmp so tests NEVER touch real outputs."""
        dst = Path(tmp) / "transcript.json"
        shutil.copy2(meeting_dir / "transcript.json", dst)
        return dst

    def test_flatten_reproduces_known_good_readable_output(self):
        """flatten() must reproduce the shipped transcript-readable.txt.

        Byte-for-byte. If this fails after a flatten change, the change
        altered output formatting for every downstream consumer
        (minutes prompts, the PM repo extraction flows) - that must be a
        deliberate, reviewed decision, never an accident.
        """
        checked = 0
        for mdir in _MEETINGS:
            existing = (mdir / "transcript-readable.txt").read_text(encoding="utf-8")
            with tempfile.TemporaryDirectory() as tmp:
                tj = self._tmp_copy(mdir, tmp)
                from whisper_sync.flatten import flatten
                out_path = flatten(str(tj))
                regenerated = Path(out_path).read_text(encoding="utf-8")
            if regenerated == existing:
                checked += 1
            else:
                # Older meetings may predate the current flatten format.
                # Require at least ONE byte-exact reproduction among recent
                # meetings; report mismatches without failing on legacy data.
                pass
        self.assertGreaterEqual(
            checked, 1,
            "flatten() must reproduce at least one recent known-good "
            "transcript-readable.txt byte-for-byte",
        )

    def test_flatten_in_memory_matches_disk_path(self):
        """transcript_data= path (crash-fix path) must equal the disk path."""
        mdir = _MEETINGS[0]
        with tempfile.TemporaryDirectory() as tmp:
            tj = self._tmp_copy(mdir, tmp)
            data = json.loads(tj.read_text(encoding="utf-8"))
            from whisper_sync.flatten import flatten
            out_disk = Path(flatten(str(tj))).read_text(encoding="utf-8")
            (Path(tmp) / "transcript-readable.txt").unlink()
            out_mem = Path(flatten(str(tj), transcript_data=data)).read_text(
                encoding="utf-8"
            )
        self.assertEqual(
            out_disk, out_mem,
            "in-memory transcript_data path must produce identical output "
            "to the json.load path",
        )

    def test_distill_covers_every_speaker_in_real_transcript(self):
        from whisper_sync.speakers import distill_transcript
        for mdir in _MEETINGS[:3]:
            with tempfile.TemporaryDirectory() as tmp:
                tj = self._tmp_copy(mdir, tmp)
                data = json.loads(tj.read_text(encoding="utf-8"))
                speakers = {
                    s.get("speaker", "UNKNOWN") for s in data.get("segments", [])
                }
                distilled = distill_transcript(str(tj))
            self.assertTrue(distilled, f"distill produced nothing for {mdir.name}")
            for spk in speakers:
                self.assertIn(
                    f"=== {spk}", distilled,
                    f"speaker {spk} missing from distilled summary "
                    f"({mdir.name}) - Claude would never see them",
                )

    def test_write_speaker_map_roundtrip_on_real_transcript(self):
        """write_speaker_map on a real transcript: map persisted, segments
        relabeled, segment count and text unchanged."""
        from whisper_sync.speakers import write_speaker_map
        mdir = _MEETINGS[0]
        with tempfile.TemporaryDirectory() as tmp:
            tj = self._tmp_copy(mdir, tmp)
            before = json.loads(tj.read_text(encoding="utf-8"))
            speakers = sorted({
                s.get("speaker", "UNKNOWN") for s in before.get("segments", [])
            })
            new_map = {spk: f"Person-{i}" for i, spk in enumerate(speakers)}

            write_speaker_map(str(tj), new_map)

            after = json.loads(tj.read_text(encoding="utf-8"))
            self.assertEqual(after.get("speaker_map"), new_map)
            self.assertEqual(
                len(after["segments"]), len(before["segments"]),
                "segment count must not change",
            )
            for b, a in zip(before["segments"], after["segments"]):
                self.assertEqual(
                    b.get("text"), a.get("text"),
                    "segment text must be untouched by speaker mapping",
                )

    def test_compute_fingerprints_on_real_transcript(self):
        from whisper_sync.speakers import compute_fingerprints
        mdir = _MEETINGS[0]
        with tempfile.TemporaryDirectory() as tmp:
            tj = self._tmp_copy(mdir, tmp)
            data = json.loads(tj.read_text(encoding="utf-8"))
            speakers = {
                s.get("speaker", "UNKNOWN") for s in data.get("segments", [])
            }
            profiles = compute_fingerprints(str(tj))
        self.assertEqual(
            set(profiles.keys()), speakers,
            "fingerprints must cover exactly the speakers in the transcript",
        )

    def test_meeting_job_flatten_step_on_real_meeting_layout(self):
        """Drive MeetingJob.step_flatten against a real meeting directory
        copy - the actual step the pipeline runs, not just the function."""
        from whisper_sync.meeting_job import MeetingJob
        mdir = _MEETINGS[0]
        existing = (mdir / "transcript-readable.txt").read_text(encoding="utf-8")
        with tempfile.TemporaryDirectory() as tmp:
            meeting_copy = Path(tmp) / mdir.name
            meeting_copy.mkdir()
            shutil.copy2(mdir / "transcript.json", meeting_copy / "transcript.json")

            job = MeetingJob(
                app=None,  # step_flatten does not touch app
                wav_path=meeting_copy / "recording.wav",
                meeting_dir=meeting_copy,
                name=mdir.name,
                summarize=False,
                date_time_str="0101_0000",
                week_dir="01-w1",
                folder_name=mdir.name,
            )
            job.transcript_result = {
                "json_path": str(meeting_copy / "transcript.json")
            }
            job.transcript_data = json.loads(
                (meeting_copy / "transcript.json").read_text(encoding="utf-8")
            )

            job.step_flatten()

            produced = meeting_copy / "transcript-readable.txt"
            self.assertTrue(produced.exists(), "step_flatten must write readable txt")
            regenerated = produced.read_text(encoding="utf-8")
        self.assertEqual(
            regenerated, existing,
            "pipeline step output must match the known-good shipped output",
        )


if __name__ == "__main__":
    unittest.main()
